language: csharp
dist: bionic
mono: latest
dotnet: 2.2
before_install:
- mono --version
- sudo apt-get update
- sudo apt-get install nuget
install:
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- dotnet restore
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- dotnet build -c Release
- if [ $TRAVIS_BRANCH != "release" ]; then mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MangoPay.SDK.Tests/bin/Release/net461/MangoPay.SDK.Tests.dll; fi
after_success:
- dotnet pack -c Release ./MangoPay.SDK/MangoPay.SDK.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./MangoPay.SDK/bin/Release/mangopay2-sdk.*.nupkg $NUGET_API_KEY -Source $NUGET_SOURCE -SkipDuplicate -Verbosity detailed
  on:
    branch: release
